// Package database owns the connection to PostgreSQL/TimescaleDB and the
// conversions between database wire types and the models.
//
// The queries themselves are generated by sqlc from database/queries and the
// goose migrations. Repositories in services/*/repository build on top of
// them; nothing outside this package talks to pgx directly.
package database

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/spioneracorei8/btcusd-trading-platform/server/constants"
)

// PoolOptions configures the pgx connection pool.
type PoolOptions struct {
	// DSN is the pgx/libpq connection string. Required.
	DSN string
	// MaxConns caps the pool size. Zero leaves the pgx default in place.
	MaxConns int32
	// ConnectTimeout bounds a single connection attempt. Zero means 5s.
	ConnectTimeout time.Duration
	// MaxConnLifetime recycles connections. Zero means 1h.
	MaxConnLifetime time.Duration
	// MaxConnIdleTime closes idle connections. Zero means 30m.
	MaxConnIdleTime time.Duration
}

// NewPool builds a pgx pool from opts.
//
// The pool connects lazily: a database that is not up yet must not stop the
// API from starting and reporting its state on /ready.
func NewPool(ctx context.Context, opts PoolOptions) (*pgxpool.Pool, error) {
	if opts.DSN == "" {
		return nil, errors.New("database: DSN is empty")
	}

	poolCfg, err := pgxpool.ParseConfig(opts.DSN)
	if err != nil {
		return nil, fmt.Errorf("parse database url: %w", err)
	}

	if opts.MaxConns > 0 {
		poolCfg.MaxConns = opts.MaxConns
	}
	poolCfg.ConnConfig.ConnectTimeout = orDuration(opts.ConnectTimeout, constants.DefaultConnectTimeout)
	poolCfg.MaxConnLifetime = orDuration(opts.MaxConnLifetime, constants.PoolMaxConnLifetime)
	poolCfg.MaxConnIdleTime = orDuration(opts.MaxConnIdleTime, constants.PoolMaxConnIdleTime)

	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("create connection pool: %w", err)
	}
	return pool, nil
}

func orDuration(d, fallback time.Duration) time.Duration {
	if d <= 0 {
		return fallback
	}
	return d
}
