// Package storage owns every conversation with PostgreSQL/TimescaleDB.
//
// Queries are generated by sqlc from internal/storage/queries and the goose
// migrations; this package wraps them so the rest of the system only ever
// sees domain types. No ORM is used.
package storage

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Sentinel errors returned by Store.
var (
	// ErrNotFound reports that a query matched no row.
	ErrNotFound = errors.New("storage: not found")
	// ErrDuplicateSignal reports that a signal for the same strategy version
	// and candle already exists, so the owner must not be notified again.
	ErrDuplicateSignal = errors.New("storage: signal already exists")
)

// PoolOptions configures the pgx connection pool.
//
// It deliberately mirrors, rather than imports, the config package: storage
// should be usable from a test or a CLI without a full application config.
type PoolOptions struct {
	// DSN is the pgx/libpq connection string. Required.
	DSN string
	// MaxConns caps the pool size. Zero leaves the pgx default in place.
	MaxConns int32
	// ConnectTimeout bounds a single connection attempt. Zero means 5s.
	ConnectTimeout time.Duration
	// MaxConnLifetime recycles connections. Zero means 1h.
	MaxConnLifetime time.Duration
	// MaxConnIdleTime closes idle connections. Zero means 30m.
	MaxConnIdleTime time.Duration
}

// Default pool tuning for a single-owner deployment on a 2 vCPU / 4 GB VPS.
const (
	defaultConnectTimeout  = 5 * time.Second
	defaultMaxConnLifetime = time.Hour
	defaultMaxConnIdleTime = 30 * time.Minute
)

// NewPool builds a pgx pool from opts.
//
// The pool connects lazily: a database that is not up yet must not stop the
// API from starting and reporting its state on /ready.
func NewPool(ctx context.Context, opts PoolOptions) (*pgxpool.Pool, error) {
	if opts.DSN == "" {
		return nil, errors.New("storage: DSN is empty")
	}

	poolCfg, err := pgxpool.ParseConfig(opts.DSN)
	if err != nil {
		return nil, fmt.Errorf("parse database url: %w", err)
	}

	if opts.MaxConns > 0 {
		poolCfg.MaxConns = opts.MaxConns
	}
	poolCfg.ConnConfig.ConnectTimeout = orDuration(opts.ConnectTimeout, defaultConnectTimeout)
	poolCfg.MaxConnLifetime = orDuration(opts.MaxConnLifetime, defaultMaxConnLifetime)
	poolCfg.MaxConnIdleTime = orDuration(opts.MaxConnIdleTime, defaultMaxConnIdleTime)

	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("create connection pool: %w", err)
	}
	return pool, nil
}

func orDuration(d, fallback time.Duration) time.Duration {
	if d <= 0 {
		return fallback
	}
	return d
}
