// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchUpsertCandle = `-- name: BatchUpsertCandle :batchexec
INSERT INTO candles (
    symbol, market_type, timeframe, open_time, close_time,
    open, high, low, close, volume, quote_volume, trade_count, is_closed
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13
)
ON CONFLICT (symbol, market_type, timeframe, open_time) DO UPDATE SET
    close_time   = EXCLUDED.close_time,
    open         = EXCLUDED.open,
    high         = EXCLUDED.high,
    low          = EXCLUDED.low,
    close        = EXCLUDED.close,
    volume       = EXCLUDED.volume,
    quote_volume = EXCLUDED.quote_volume,
    trade_count  = EXCLUDED.trade_count,
    is_closed    = EXCLUDED.is_closed
`

type BatchUpsertCandleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertCandleParams struct {
	Symbol      string
	MarketType  string
	Timeframe   string
	OpenTime    pgtype.Timestamptz
	CloseTime   pgtype.Timestamptz
	Open        pgtype.Numeric
	High        pgtype.Numeric
	Low         pgtype.Numeric
	Close       pgtype.Numeric
	Volume      pgtype.Numeric
	QuoteVolume pgtype.Numeric
	TradeCount  int32
	IsClosed    bool
}

// The batched form of UpsertCandle, used by backfill.
//
// pgx sends the whole batch in one round trip, so a three year backfill costs
// thousands of round trips rather than millions. The conflict clause is
// identical to the single-row version: re-running a backfill over data that is
// already stored must change nothing.
func (q *Queries) BatchUpsertCandle(ctx context.Context, arg []BatchUpsertCandleParams) *BatchUpsertCandleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Symbol,
			a.MarketType,
			a.Timeframe,
			a.OpenTime,
			a.CloseTime,
			a.Open,
			a.High,
			a.Low,
			a.Close,
			a.Volume,
			a.QuoteVolume,
			a.TradeCount,
			a.IsClosed,
		}
		batch.Queue(batchUpsertCandle, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertCandleBatchResults{br, len(arg), false}
}

func (b *BatchUpsertCandleBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertCandleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
