// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: candles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCandles = `-- name: CountCandles :one
SELECT count(*) FROM candles
WHERE symbol = $1
  AND market_type = $2
  AND timeframe = $3
`

type CountCandlesParams struct {
	Symbol     string
	MarketType string
	Timeframe  string
}

// Row count for a symbol/market/timeframe; used by tests to prove that
// repeating an upsert does not create a second row.
func (q *Queries) CountCandles(ctx context.Context, arg CountCandlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandles, arg.Symbol, arg.MarketType, arg.Timeframe)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findCandleGaps = `-- name: FindCandleGaps :many
WITH ordered AS (
    SELECT
        open_time,
        LAG(open_time) OVER (ORDER BY open_time) AS previous_open_time
    FROM candles
    WHERE symbol = $2
      AND market_type = $3
      AND timeframe = $4
)
SELECT
    (previous_open_time + $1::interval)::timestamptz AS gap_start,
    open_time::timestamptz AS gap_end
FROM ordered
WHERE previous_open_time IS NOT NULL
  AND open_time - previous_open_time > $1::interval
ORDER BY gap_start
`

type FindCandleGapsParams struct {
	Interval   pgtype.Interval
	Symbol     string
	MarketType string
	Timeframe  string
}

type FindCandleGapsRow struct {
	GapStart pgtype.Timestamptz
	GapEnd   pgtype.Timestamptz
}

// Holes in the expected sequence, found with a window function.
//
// The diff is computed in the database on purpose: pulling three years of 1m
// candles into Go to difference them would move hundreds of megabytes to
// discover a handful of gaps.
//
// gap_start is the open time of the first MISSING candle and gap_end the open
// time of the first candle present again, which is the convention
// models.DataGap documents.
func (q *Queries) FindCandleGaps(ctx context.Context, arg FindCandleGapsParams) ([]FindCandleGapsRow, error) {
	rows, err := q.db.Query(ctx, findCandleGaps,
		arg.Interval,
		arg.Symbol,
		arg.MarketType,
		arg.Timeframe,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindCandleGapsRow{}
	for rows.Next() {
		var i FindCandleGapsRow
		if err := rows.Scan(&i.GapStart, &i.GapEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandles = `-- name: GetCandles :many
SELECT symbol, market_type, timeframe, open_time, close_time, open, high, low, close, volume, quote_volume, trade_count, is_closed, created_at FROM candles
WHERE symbol = $1
  AND market_type = $2
  AND timeframe = $3
  AND open_time >= $4
  AND open_time <= $5
ORDER BY open_time
`

type GetCandlesParams struct {
	Symbol     string
	MarketType string
	Timeframe  string
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

// Closed candles in [from_time, to_time], oldest first. The bounds are
// inclusive on open_time so a caller asking for a window gets exactly the
// bars whose open falls inside it.
func (q *Queries) GetCandles(ctx context.Context, arg GetCandlesParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getCandles,
		arg.Symbol,
		arg.MarketType,
		arg.Timeframe,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Candle{}
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.Symbol,
			&i.MarketType,
			&i.Timeframe,
			&i.OpenTime,
			&i.CloseTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.QuoteVolume,
			&i.TradeCount,
			&i.IsClosed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarliestCandle = `-- name: GetEarliestCandle :one
SELECT symbol, market_type, timeframe, open_time, close_time, open, high, low, close, volume, quote_volume, trade_count, is_closed, created_at FROM candles
WHERE symbol = $1
  AND market_type = $2
  AND timeframe = $3
ORDER BY open_time
LIMIT 1
`

type GetEarliestCandleParams struct {
	Symbol     string
	MarketType string
	Timeframe  string
}

// Oldest stored candle for a series, which bounds the expected sequence.
func (q *Queries) GetEarliestCandle(ctx context.Context, arg GetEarliestCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, getEarliestCandle, arg.Symbol, arg.MarketType, arg.Timeframe)
	var i Candle
	err := row.Scan(
		&i.Symbol,
		&i.MarketType,
		&i.Timeframe,
		&i.OpenTime,
		&i.CloseTime,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.QuoteVolume,
		&i.TradeCount,
		&i.IsClosed,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCandle = `-- name: GetLatestCandle :one
SELECT symbol, market_type, timeframe, open_time, close_time, open, high, low, close, volume, quote_volume, trade_count, is_closed, created_at FROM candles
WHERE symbol = $1
  AND market_type = $2
  AND timeframe = $3
ORDER BY open_time DESC
LIMIT 1
`

type GetLatestCandleParams struct {
	Symbol     string
	MarketType string
	Timeframe  string
}

// Most recent stored candle, used to work out where a backfill must resume.
func (q *Queries) GetLatestCandle(ctx context.Context, arg GetLatestCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, getLatestCandle, arg.Symbol, arg.MarketType, arg.Timeframe)
	var i Candle
	err := row.Scan(
		&i.Symbol,
		&i.MarketType,
		&i.Timeframe,
		&i.OpenTime,
		&i.CloseTime,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.QuoteVolume,
		&i.TradeCount,
		&i.IsClosed,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCandle = `-- name: UpsertCandle :exec
INSERT INTO candles (
    symbol, market_type, timeframe, open_time, close_time,
    open, high, low, close, volume, quote_volume, trade_count, is_closed
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13
)
ON CONFLICT (symbol, market_type, timeframe, open_time) DO UPDATE SET
    close_time   = EXCLUDED.close_time,
    open         = EXCLUDED.open,
    high         = EXCLUDED.high,
    low          = EXCLUDED.low,
    close        = EXCLUDED.close,
    volume       = EXCLUDED.volume,
    quote_volume = EXCLUDED.quote_volume,
    trade_count  = EXCLUDED.trade_count,
    is_closed    = EXCLUDED.is_closed
`

type UpsertCandleParams struct {
	Symbol      string
	MarketType  string
	Timeframe   string
	OpenTime    pgtype.Timestamptz
	CloseTime   pgtype.Timestamptz
	Open        pgtype.Numeric
	High        pgtype.Numeric
	Low         pgtype.Numeric
	Close       pgtype.Numeric
	Volume      pgtype.Numeric
	QuoteVolume pgtype.Numeric
	TradeCount  int32
	IsClosed    bool
}

// Idempotent write of one closed candle. Re-delivering the same bar (after a
// reconnect or a REST backfill) updates it in place instead of duplicating it.
func (q *Queries) UpsertCandle(ctx context.Context, arg UpsertCandleParams) error {
	_, err := q.db.Exec(ctx, upsertCandle,
		arg.Symbol,
		arg.MarketType,
		arg.Timeframe,
		arg.OpenTime,
		arg.CloseTime,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.QuoteVolume,
		arg.TradeCount,
		arg.IsClosed,
	)
	return err
}
