// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collector_status.sql

package db

import (
	"context"
)

const getCollectorStatus = `-- name: GetCollectorStatus :one
SELECT symbol, market_type, ws_connected, last_connected_at, last_disconnected_at, last_disconnect_note, reconnect_count, started_at, updated_at FROM collector_status
WHERE symbol = $1
  AND market_type = $2
`

type GetCollectorStatusParams struct {
	Symbol     string
	MarketType string
}

func (q *Queries) GetCollectorStatus(ctx context.Context, arg GetCollectorStatusParams) (CollectorStatus, error) {
	row := q.db.QueryRow(ctx, getCollectorStatus, arg.Symbol, arg.MarketType)
	var i CollectorStatus
	err := row.Scan(
		&i.Symbol,
		&i.MarketType,
		&i.WsConnected,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastDisconnectNote,
		&i.ReconnectCount,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatCollector = `-- name: HeartbeatCollector :exec
UPDATE collector_status SET
    ws_connected = $1,
    updated_at   = now()
WHERE symbol = $2
  AND market_type = $3
`

type HeartbeatCollectorParams struct {
	WsConnected bool
	Symbol      string
	MarketType  string
}

// Called on every heartbeat tick. Deliberately leaves started_at untouched.
func (q *Queries) HeartbeatCollector(ctx context.Context, arg HeartbeatCollectorParams) error {
	_, err := q.db.Exec(ctx, heartbeatCollector, arg.WsConnected, arg.Symbol, arg.MarketType)
	return err
}

const markCollectorConnected = `-- name: MarkCollectorConnected :exec
UPDATE collector_status SET
    ws_connected      = true,
    last_connected_at = now(),
    reconnect_count   = reconnect_count + $1::int,
    updated_at        = now()
WHERE symbol = $2
  AND market_type = $3
`

type MarkCollectorConnectedParams struct {
	ReconnectIncrement int32
	Symbol             string
	MarketType         string
}

// Called when the stream comes up.
func (q *Queries) MarkCollectorConnected(ctx context.Context, arg MarkCollectorConnectedParams) error {
	_, err := q.db.Exec(ctx, markCollectorConnected, arg.ReconnectIncrement, arg.Symbol, arg.MarketType)
	return err
}

const markCollectorDisconnected = `-- name: MarkCollectorDisconnected :exec
UPDATE collector_status SET
    ws_connected         = false,
    last_disconnected_at = now(),
    last_disconnect_note = $1,
    updated_at           = now()
WHERE symbol = $2
  AND market_type = $3
`

type MarkCollectorDisconnectedParams struct {
	Note       string
	Symbol     string
	MarketType string
}

// Called when the stream goes down, with the reason kept for later.
func (q *Queries) MarkCollectorDisconnected(ctx context.Context, arg MarkCollectorDisconnectedParams) error {
	_, err := q.db.Exec(ctx, markCollectorDisconnected, arg.Note, arg.Symbol, arg.MarketType)
	return err
}

const registerCollectorStart = `-- name: RegisterCollectorStart :one
INSERT INTO collector_status (
    symbol, market_type, ws_connected, started_at, updated_at
) VALUES (
    $1, $2, false, now(), now()
)
ON CONFLICT (symbol, market_type) DO UPDATE SET
    ws_connected         = false,
    last_disconnected_at = NULL,
    last_disconnect_note = '',
    reconnect_count      = 0,
    started_at           = now(),
    updated_at           = now()
RETURNING symbol, market_type, ws_connected, last_connected_at, last_disconnected_at, last_disconnect_note, reconnect_count, started_at, updated_at
`

type RegisterCollectorStartParams struct {
	Symbol     string
	MarketType string
}

// Called once when the collector process starts.
//
// This is the only statement that writes started_at, so a heartbeat cannot
// disguise a crash loop as continuous uptime: a process that keeps restarting
// moves started_at forward every time, while one that has been up for days
// leaves it alone.
func (q *Queries) RegisterCollectorStart(ctx context.Context, arg RegisterCollectorStartParams) (CollectorStatus, error) {
	row := q.db.QueryRow(ctx, registerCollectorStart, arg.Symbol, arg.MarketType)
	var i CollectorStatus
	err := row.Scan(
		&i.Symbol,
		&i.MarketType,
		&i.WsConnected,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastDisconnectNote,
		&i.ReconnectCount,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}
