// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collector_status.sql

package db

import (
	"context"
)

const getCollectorStatus = `-- name: GetCollectorStatus :one
SELECT symbol, market_type, ws_connected, last_connected_at, last_disconnected_at, last_disconnect_note, reconnect_count, started_at, updated_at, state, state_changed_at, strategy_name, strategy_timeframe, evaluator_ready, evaluator_reason FROM collector_status
WHERE symbol = $1
  AND market_type = $2
`

type GetCollectorStatusParams struct {
	Symbol     string
	MarketType string
}

func (q *Queries) GetCollectorStatus(ctx context.Context, arg GetCollectorStatusParams) (CollectorStatus, error) {
	row := q.db.QueryRow(ctx, getCollectorStatus, arg.Symbol, arg.MarketType)
	var i CollectorStatus
	err := row.Scan(
		&i.Symbol,
		&i.MarketType,
		&i.WsConnected,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastDisconnectNote,
		&i.ReconnectCount,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.State,
		&i.StateChangedAt,
		&i.StrategyName,
		&i.StrategyTimeframe,
		&i.EvaluatorReady,
		&i.EvaluatorReason,
	)
	return i, err
}

const heartbeatCollector = `-- name: HeartbeatCollector :exec
UPDATE collector_status SET
    ws_connected       = $1,
    strategy_name      = $2,
    strategy_timeframe = $3,
    evaluator_ready    = $4,
    evaluator_reason   = $5,
    updated_at         = now()
WHERE symbol = $6
  AND market_type = $7
`

type HeartbeatCollectorParams struct {
	WsConnected       bool
	StrategyName      string
	StrategyTimeframe string
	EvaluatorReady    bool
	EvaluatorReason   string
	Symbol            string
	MarketType        string
}

// Called on every heartbeat tick. Deliberately leaves started_at untouched.
//
// The evaluator's state rides along with it. The api is a separate process and
// cannot see the collector's memory, so readiness that is never written down
// is readiness nobody outside can observe — and "warming up", "refusing to
// evaluate" and "found no setup" are indistinguishable from a distance.
func (q *Queries) HeartbeatCollector(ctx context.Context, arg HeartbeatCollectorParams) error {
	_, err := q.db.Exec(ctx, heartbeatCollector,
		arg.WsConnected,
		arg.StrategyName,
		arg.StrategyTimeframe,
		arg.EvaluatorReady,
		arg.EvaluatorReason,
		arg.Symbol,
		arg.MarketType,
	)
	return err
}

const markCollectorConnected = `-- name: MarkCollectorConnected :exec
UPDATE collector_status SET
    ws_connected      = true,
    last_connected_at = now(),
    reconnect_count   = reconnect_count + $1::int,
    updated_at        = now()
WHERE symbol = $2
  AND market_type = $3
`

type MarkCollectorConnectedParams struct {
	ReconnectIncrement int32
	Symbol             string
	MarketType         string
}

// Called when the stream comes up.
func (q *Queries) MarkCollectorConnected(ctx context.Context, arg MarkCollectorConnectedParams) error {
	_, err := q.db.Exec(ctx, markCollectorConnected, arg.ReconnectIncrement, arg.Symbol, arg.MarketType)
	return err
}

const markCollectorDisconnected = `-- name: MarkCollectorDisconnected :exec
UPDATE collector_status SET
    ws_connected         = false,
    last_disconnected_at = now(),
    last_disconnect_note = $1,
    updated_at           = now()
WHERE symbol = $2
  AND market_type = $3
`

type MarkCollectorDisconnectedParams struct {
	Note       string
	Symbol     string
	MarketType string
}

// Called when the stream goes down, with the reason kept for later.
func (q *Queries) MarkCollectorDisconnected(ctx context.Context, arg MarkCollectorDisconnectedParams) error {
	_, err := q.db.Exec(ctx, markCollectorDisconnected, arg.Note, arg.Symbol, arg.MarketType)
	return err
}

const registerCollectorStart = `-- name: RegisterCollectorStart :one
INSERT INTO collector_status (
    symbol, market_type, ws_connected, state, state_changed_at, started_at, updated_at
) VALUES (
    $1, $2, false, 'starting', now(), now(), now()
)
ON CONFLICT (symbol, market_type) DO UPDATE SET
    ws_connected         = false,
    last_disconnected_at = NULL,
    last_disconnect_note = '',
    reconnect_count      = 0,
    state                = 'starting',
    state_changed_at     = now(),
    started_at           = now(),
    updated_at           = now()
RETURNING symbol, market_type, ws_connected, last_connected_at, last_disconnected_at, last_disconnect_note, reconnect_count, started_at, updated_at, state, state_changed_at, strategy_name, strategy_timeframe, evaluator_ready, evaluator_reason
`

type RegisterCollectorStartParams struct {
	Symbol     string
	MarketType string
}

// Called once when the collector process starts.
//
// This is the only statement that writes started_at, so a heartbeat cannot
// disguise a crash loop as continuous uptime: a process that keeps restarting
// moves started_at forward every time, while one that has been up for days
// leaves it alone.
func (q *Queries) RegisterCollectorStart(ctx context.Context, arg RegisterCollectorStartParams) (CollectorStatus, error) {
	row := q.db.QueryRow(ctx, registerCollectorStart, arg.Symbol, arg.MarketType)
	var i CollectorStatus
	err := row.Scan(
		&i.Symbol,
		&i.MarketType,
		&i.WsConnected,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastDisconnectNote,
		&i.ReconnectCount,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.State,
		&i.StateChangedAt,
		&i.StrategyName,
		&i.StrategyTimeframe,
		&i.EvaluatorReady,
		&i.EvaluatorReason,
	)
	return i, err
}

const setCollectorState = `-- name: SetCollectorState :exec
UPDATE collector_status SET
    state            = $1,
    state_changed_at = CASE WHEN state IS DISTINCT FROM $1 THEN now() ELSE state_changed_at END,
    updated_at       = now()
WHERE symbol = $2
  AND market_type = $3
`

type SetCollectorStateParams struct {
	State      string
	Symbol     string
	MarketType string
}

// Records a lifecycle transition. state_changed_at only moves when the state
// actually changes, so the time spent in a state is measurable.
func (q *Queries) SetCollectorState(ctx context.Context, arg SetCollectorStateParams) error {
	_, err := q.db.Exec(ctx, setCollectorState, arg.State, arg.Symbol, arg.MarketType)
	return err
}
