// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package db

import (
	"context"
)

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = 1
`

// Forget the registered device, so notify mode stops claiming it can deliver.
func (q *Queries) DeleteDevice(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchDevice = `-- name: FetchDevice :one
SELECT id, platform, label, registered_at, refreshed_at, endpoint, p256dh, auth FROM devices WHERE id = 1
`

// The registered device, or no row when the phone has never registered.
func (q *Queries) FetchDevice(ctx context.Context) (Device, error) {
	row := q.db.QueryRow(ctx, fetchDevice)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.RegisteredAt,
		&i.RefreshedAt,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
	)
	return i, err
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO devices (id, endpoint, p256dh, auth, platform, label)
VALUES (1, $1, $2, $3,
        $4, $5)
ON CONFLICT (id) DO UPDATE
SET endpoint = EXCLUDED.endpoint,
    p256dh   = EXCLUDED.p256dh,
    auth     = EXCLUDED.auth,
    platform = EXCLUDED.platform,
    label    = EXCLUDED.label,
    registered_at = CASE
        WHEN devices.endpoint = EXCLUDED.endpoint THEN devices.registered_at
        ELSE now()
    END,
    refreshed_at = now()
RETURNING id, platform, label, registered_at, refreshed_at, endpoint, p256dh, auth
`

type RegisterDeviceParams struct {
	Endpoint string
	P256dh   string
	Auth     string
	Platform string
	Label    string
}

// Record the phone this deployment delivers to, replacing whatever was there.
//
// Upsert on the singleton row rather than insert-if-absent: a push
// subscription expires, and is replaced outright by a reinstall or a browser
// clearing site data. The app re-subscribes on every launch and posts the
// result. A statement that refused the second registration would leave the
// deployment holding a subscription the push service has already retired,
// which fails permanently on the next signal and looks like a broken strategy
// rather than a stale registration.
//
// registered_at is kept when the endpoint is unchanged and reset when it is
// not. The endpoint is the identity: the keys are rotated with it, so two
// registrations sharing an endpoint are the same phone still there.
func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerDevice,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.Platform,
		arg.Label,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.RegisteredAt,
		&i.RefreshedAt,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
	)
	return i, err
}
