// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package db

import (
	"context"
)

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = 1
`

// Forget the registered device, so notify mode stops claiming it can deliver.
func (q *Queries) DeleteDevice(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fetchDevice = `-- name: FetchDevice :one
SELECT id, token, platform, label, registered_at, refreshed_at FROM devices WHERE id = 1
`

// The registered device, or no row when the phone has never registered.
func (q *Queries) FetchDevice(ctx context.Context) (Device, error) {
	row := q.db.QueryRow(ctx, fetchDevice)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Platform,
		&i.Label,
		&i.RegisteredAt,
		&i.RefreshedAt,
	)
	return i, err
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO devices (id, token, platform, label)
VALUES (1, $1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET token    = EXCLUDED.token,
    platform = EXCLUDED.platform,
    label    = EXCLUDED.label,
    registered_at = CASE
        WHEN devices.token = EXCLUDED.token THEN devices.registered_at
        ELSE now()
    END,
    refreshed_at = now()
RETURNING id, token, platform, label, registered_at, refreshed_at
`

type RegisterDeviceParams struct {
	Token    string
	Platform string
	Label    string
}

// Record the phone this deployment delivers to, replacing whatever was there.
//
// Upsert on the singleton row rather than insert-if-absent: FCM rotates
// tokens, and the app re-registers on every refresh. A statement that
// refused the second registration would leave the deployment holding a token
// Firebase has already retired, which fails permanently on the next signal
// and looks like a broken strategy rather than a stale token.
//
// registered_at is kept when the token is unchanged and reset when it is not:
// a refresh of the same token is the same phone still there, a different
// token is a new registration.
func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerDevice, arg.Token, arg.Platform, arg.Label)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Platform,
		&i.Label,
		&i.RegisteredAt,
		&i.RefreshedAt,
	)
	return i, err
}
