// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candle struct {
	Symbol      string
	MarketType  string
	Timeframe   string
	OpenTime    pgtype.Timestamptz
	CloseTime   pgtype.Timestamptz
	Open        pgtype.Numeric
	High        pgtype.Numeric
	Low         pgtype.Numeric
	Close       pgtype.Numeric
	Volume      pgtype.Numeric
	QuoteVolume pgtype.Numeric
	TradeCount  int32
	IsClosed    bool
	CreatedAt   pgtype.Timestamptz
}

type CollectorStatus struct {
	Symbol             string
	MarketType         string
	WsConnected        bool
	LastConnectedAt    pgtype.Timestamptz
	LastDisconnectedAt pgtype.Timestamptz
	LastDisconnectNote string
	ReconnectCount     int32
	StartedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type DataGap struct {
	ID           int64
	Symbol       string
	MarketType   string
	Timeframe    string
	GapStart     pgtype.Timestamptz
	GapEnd       pgtype.Timestamptz
	DetectedAt   pgtype.Timestamptz
	FilledAt     pgtype.Timestamptz
	Note         string
	FillAttempts int32
}

type Notification struct {
	ID        int64
	SignalID  pgtype.UUID
	Channel   string
	Status    string
	Attempts  int32
	LastError string
	SentAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Signal struct {
	ID              pgtype.UUID
	Symbol          string
	MarketType      string
	Timeframe       string
	SignalTime      pgtype.Timestamptz
	Direction       string
	Strength        pgtype.Numeric
	EntryPrice      pgtype.Numeric
	StopLoss        pgtype.Numeric
	TakeProfit      pgtype.Numeric
	StrategyName    string
	StrategyVersion string
	Reason          []byte
	CreatedAt       pgtype.Timestamptz
}
