// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candle struct {
	Symbol      string
	MarketType  string
	Timeframe   string
	OpenTime    pgtype.Timestamptz
	CloseTime   pgtype.Timestamptz
	Open        pgtype.Numeric
	High        pgtype.Numeric
	Low         pgtype.Numeric
	Close       pgtype.Numeric
	Volume      pgtype.Numeric
	QuoteVolume pgtype.Numeric
	TradeCount  int32
	IsClosed    bool
	CreatedAt   pgtype.Timestamptz
}

type CollectorStatus struct {
	Symbol             string
	MarketType         string
	WsConnected        bool
	LastConnectedAt    pgtype.Timestamptz
	LastDisconnectedAt pgtype.Timestamptz
	LastDisconnectNote string
	ReconnectCount     int32
	StartedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	State              string
	StateChangedAt     pgtype.Timestamptz
	StrategyName       string
	StrategyTimeframe  string
	EvaluatorReady     bool
	// Why the evaluator is not deciding, when it is not. Empty when it is, and when no strategy is configured at all — strategy_name distinguishes those.
	EvaluatorReason string
}

type DataGap struct {
	ID           int64
	Symbol       string
	MarketType   string
	Timeframe    string
	GapStart     pgtype.Timestamptz
	GapEnd       pgtype.Timestamptz
	DetectedAt   pgtype.Timestamptz
	FilledAt     pgtype.Timestamptz
	Note         string
	FillAttempts int32
}

type Device struct {
	ID           int32
	Platform     string
	Label        string
	RegisteredAt pgtype.Timestamptz
	RefreshedAt  pgtype.Timestamptz
	Endpoint     string
	P256dh       string
	Auth         string
}

type Notification struct {
	ID        int64
	SignalID  pgtype.UUID
	Channel   string
	Status    string
	Attempts  int32
	LastError string
	SentAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	// Not before this instant. Set into the future by a failed attempt so the backoff outlives the process that decided it.
	NextAttemptAt pgtype.Timestamptz
}

type Signal struct {
	ID              pgtype.UUID
	Symbol          string
	MarketType      string
	Timeframe       string
	SignalTime      pgtype.Timestamptz
	Direction       string
	Strength        pgtype.Numeric
	EntryPrice      pgtype.Numeric
	StopLoss        pgtype.Numeric
	TakeProfit      pgtype.Numeric
	StrategyName    string
	StrategyVersion string
	Reason          []byte
	CreatedAt       pgtype.Timestamptz
	// The close the strategy decided on. entry_price is what a position would have been opened at: the next bar's open plus slippage, filled in once that bar closes.
	SignalPrice pgtype.Numeric
}

type SignalOutcome struct {
	SignalID          pgtype.UUID
	Status            string
	ResolvedAt        pgtype.Timestamptz
	ResolvedPrice     pgtype.Numeric
	Mae               pgtype.Numeric
	Mfe               pgtype.Numeric
	BarsHeld          int32
	BacktestWouldHave []byte
	DivergenceNote    string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
