// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchPendingNotifications = `-- name: FetchPendingNotifications :many
SELECT id, signal_id, channel, status, attempts, last_error, sent_at, created_at FROM notifications
WHERE status = 'pending'
ORDER BY created_at, id
LIMIT $1
`

// The delivery queue, oldest first, so a backlog drains in the order the
// signals happened rather than newest-first.
func (q *Queries) FetchPendingNotifications(ctx context.Context, rowLimit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, fetchPendingNotifications, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.SignalID,
			&i.Channel,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (signal_id, channel)
VALUES ($1, $2)
ON CONFLICT (signal_id, channel) DO NOTHING
RETURNING id, signal_id, channel, status, attempts, last_error, sent_at, created_at
`

type InsertNotificationParams struct {
	SignalID pgtype.UUID
	Channel  string
}

// Queue one signal for delivery.
//
// ON CONFLICT DO NOTHING makes queuing idempotent: the same signal offered
// twice — by a retry, or by a restart that re-walked a bar — leaves the one
// row that is already there. No row comes back in that case, which the
// repository reads as "already queued" rather than as a failure.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification, arg.SignalID, arg.Channel)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.SignalID,
		&i.Channel,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}
