// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pipeline.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pipelineDeliveryActivity = `-- name: PipelineDeliveryActivity :one
SELECT
    count(*) FILTER (WHERE n.status = 'pending')::bigint AS pending,
    count(*) FILTER (WHERE n.status = 'sent')::bigint    AS sent,
    count(*) FILTER (WHERE n.status = 'failed')::bigint  AS failed,
    (max(n.sent_at) FILTER (WHERE n.status = 'sent'))::timestamptz AS last_sent_at
FROM notifications n
JOIN signals s ON s.id = n.signal_id
WHERE s.symbol = $1
  AND s.market_type = $2
`

type PipelineDeliveryActivityParams struct {
	Symbol     string
	MarketType string
}

type PipelineDeliveryActivityRow struct {
	Pending    int64
	Sent       int64
	Failed     int64
	LastSentAt pgtype.Timestamptz
}

// The delivery queue, by state.
//
// failed is the number that matters: nothing retries a failed row, so a
// delivery path that is permanently broken shows up here and nowhere else.
func (q *Queries) PipelineDeliveryActivity(ctx context.Context, arg PipelineDeliveryActivityParams) (PipelineDeliveryActivityRow, error) {
	row := q.db.QueryRow(ctx, pipelineDeliveryActivity, arg.Symbol, arg.MarketType)
	var i PipelineDeliveryActivityRow
	err := row.Scan(
		&i.Pending,
		&i.Sent,
		&i.Failed,
		&i.LastSentAt,
	)
	return i, err
}

const pipelineSignalActivity = `-- name: PipelineSignalActivity :one
SELECT
    (SELECT max(s.signal_time) FROM signals s
      WHERE s.symbol = $1 AND s.market_type = $2
    )::timestamptz AS last_signal_at,

    (SELECT count(*) FROM signals s
      WHERE s.symbol = $1 AND s.market_type = $2
    )::bigint AS signals_total,

    (SELECT count(*) FROM signals s
      JOIN signal_outcomes o ON o.signal_id = s.id
      WHERE s.symbol = $1 AND s.market_type = $2
        AND o.status = 'open'
    )::bigint AS outcomes_open,

    -- The oldest signal still being followed. A follower that has stopped
    -- shows up here as an age that keeps growing, which is the only symptom
    -- it has.
    (SELECT min(s.signal_time) FROM signals s
      JOIN signal_outcomes o ON o.signal_id = s.id
      WHERE s.symbol = $1 AND s.market_type = $2
        AND o.status = 'open'
    )::timestamptz AS oldest_open_signal_at,

    -- Signals with no outcome row at all. Non-zero for longer than a pass
    -- means the follower is not opening them.
    (SELECT count(*) FROM signals s
      LEFT JOIN signal_outcomes o ON o.signal_id = s.id
      WHERE s.symbol = $1 AND s.market_type = $2
        AND o.signal_id IS NULL
    )::bigint AS outcomes_missing
`

type PipelineSignalActivityParams struct {
	Symbol     string
	MarketType string
}

type PipelineSignalActivityRow struct {
	LastSignalAt       pgtype.Timestamptz
	SignalsTotal       int64
	OutcomesOpen       int64
	OldestOpenSignalAt pgtype.Timestamptz
	OutcomesMissing    int64
}

// When the signal pipeline last produced anything, and how much is waiting.
//
// One row, because a status endpoint that made five round trips would report
// five different instants and invite the reader to reconcile them.
func (q *Queries) PipelineSignalActivity(ctx context.Context, arg PipelineSignalActivityParams) (PipelineSignalActivityRow, error) {
	row := q.db.QueryRow(ctx, pipelineSignalActivity, arg.Symbol, arg.MarketType)
	var i PipelineSignalActivityRow
	err := row.Scan(
		&i.LastSignalAt,
		&i.SignalsTotal,
		&i.OutcomesOpen,
		&i.OldestOpenSignalAt,
		&i.OutcomesMissing,
	)
	return i, err
}
