// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reconciliation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reconcileLiveSignals = `-- name: ReconcileLiveSignals :many
SELECT
    s.strategy_name,
    s.strategy_version,
    (COALESCE(s.reason -> 'strategy' -> 'params', '[]'::jsonb))::jsonb AS params,

    s.signal_time,
    s.entry_price,

    o.status,
    o.bars_held,
    (o.divergence_note <> '') AS rested_on_assumption,

    -- Null while a signal is open, and for one whose window had missing data:
    -- what happened there is not knowable, and a number would make a guess
    -- look like a measurement.
    ((o.backtest_would_have ->> 'net_return_pct')::numeric) AS net_return_pct,
    ((o.backtest_would_have ->> 'cost_pct')::numeric)       AS cost_pct
FROM signals s
JOIN signal_outcomes o ON o.signal_id = s.id
WHERE s.symbol = $1
  AND s.market_type = $2
  AND s.signal_time >= $3
  AND s.signal_time <= $4
ORDER BY s.strategy_name, s.strategy_version, s.signal_time
`

type ReconcileLiveSignalsParams struct {
	Symbol     string
	MarketType string
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

type ReconcileLiveSignalsRow struct {
	StrategyName       string
	StrategyVersion    string
	Params             []byte
	SignalTime         pgtype.Timestamptz
	EntryPrice         pgtype.Numeric
	Status             string
	BarsHeld           int32
	RestedOnAssumption bool
	NetReturnPct       pgtype.Numeric
	CostPct            pgtype.Numeric
}

// Every live signal in the window, one row each, with what became of it.
//
// # Why rows rather than an aggregate
//
// The report needs three views of the same population: everything the live
// path produced, the subset the engine also emitted, and the surplus it did
// not. Which signals fall in which is only knowable after the engine has run,
// so the split cannot be pushed into SQL without running the engine first and
// passing its timestamps back in.
//
// One projection and one aggregation in Go is the alternative to three
// aggregates that must agree. The window is bounded and the strategies here
// trade at most a few times a day, so the row count is small.
//
// The grouping key comes back with each row: a parameter change between two
// signals leaves two incomparable groups, and averaging across it produces a
// number describing nothing.
func (q *Queries) ReconcileLiveSignals(ctx context.Context, arg ReconcileLiveSignalsParams) ([]ReconcileLiveSignalsRow, error) {
	rows, err := q.db.Query(ctx, reconcileLiveSignals,
		arg.Symbol,
		arg.MarketType,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileLiveSignalsRow{}
	for rows.Next() {
		var i ReconcileLiveSignalsRow
		if err := rows.Scan(
			&i.StrategyName,
			&i.StrategyVersion,
			&i.Params,
			&i.SignalTime,
			&i.EntryPrice,
			&i.Status,
			&i.BarsHeld,
			&i.RestedOnAssumption,
			&i.NetReturnPct,
			&i.CostPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
