// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reconciliation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reconcileLiveGroups = `-- name: ReconcileLiveGroups :many
SELECT
    s.strategy_name,
    s.strategy_version,
    (COALESCE(s.reason -> 'strategy' -> 'params', '[]'::jsonb))::jsonb AS params,

    count(*)                                            AS signals,
    count(*) FILTER (WHERE o.status = 'open')           AS still_open,
    count(*) FILTER (WHERE o.status = 'invalidated')    AS invalidated,
    count(*) FILTER (WHERE o.status IN ('target', 'stop', 'expired')) AS resolved,

    count(*) FILTER (WHERE o.status = 'target')         AS targets,
    count(*) FILTER (WHERE o.status = 'stop')           AS stops,
    count(*) FILTER (WHERE o.status = 'expired')        AS expired,

    -- Resolutions that rested on an assumption rather than on the data: a bar
    -- reaching both levels, or an entry that gapped past one.
    count(*) FILTER (WHERE o.status IN ('target', 'stop', 'expired')
                       AND o.divergence_note <> '')     AS noted,

    count(*) FILTER (WHERE o.status IN ('target', 'stop', 'expired')
                       AND (o.backtest_would_have ->> 'net_return_pct')::numeric > 0) AS wins,
    count(*) FILTER (WHERE o.status IN ('target', 'stop', 'expired')
                       AND (o.backtest_would_have ->> 'net_return_pct')::numeric <= 0) AS losses,

    (avg((o.backtest_would_have ->> 'net_return_pct')::numeric)
        FILTER (WHERE o.status IN ('target', 'stop', 'expired')
                  AND (o.backtest_would_have ->> 'net_return_pct')::numeric > 0))::numeric  AS average_win_pct,
    (avg((o.backtest_would_have ->> 'net_return_pct')::numeric)
        FILTER (WHERE o.status IN ('target', 'stop', 'expired')
                  AND (o.backtest_would_have ->> 'net_return_pct')::numeric <= 0))::numeric AS average_loss_pct,

    -- The cost actually modelled on these signals, so the report quotes what
    -- was applied rather than what the configuration currently says.
    (avg((o.backtest_would_have ->> 'cost_pct')::numeric)
        FILTER (WHERE o.status IN ('target', 'stop', 'expired')))::numeric        AS average_cost_pct,

    (avg(s.entry_price) FILTER (WHERE s.entry_price IS NOT NULL))::numeric        AS average_entry_price,
    (avg(o.bars_held) FILTER (WHERE o.status IN ('target', 'stop', 'expired')))::numeric AS average_bars_held,

    (min(s.signal_time))::timestamptz AS first_signal,
    (max(s.signal_time))::timestamptz AS last_signal
FROM signals s
JOIN signal_outcomes o ON o.signal_id = s.id
WHERE s.symbol = $1
  AND s.market_type = $2
  AND s.signal_time >= $3
  AND s.signal_time <= $4
GROUP BY s.strategy_name, s.strategy_version, COALESCE(s.reason -> 'strategy' -> 'params', '[]'::jsonb)
ORDER BY s.strategy_name, s.strategy_version, min(s.signal_time)
`

type ReconcileLiveGroupsParams struct {
	Symbol     string
	MarketType string
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

type ReconcileLiveGroupsRow struct {
	StrategyName      string
	StrategyVersion   string
	Params            []byte
	Signals           int64
	StillOpen         int64
	Invalidated       int64
	Resolved          int64
	Targets           int64
	Stops             int64
	Expired           int64
	Noted             int64
	Wins              int64
	Losses            int64
	AverageWinPct     pgtype.Numeric
	AverageLossPct    pgtype.Numeric
	AverageCostPct    pgtype.Numeric
	AverageEntryPrice pgtype.Numeric
	AverageBarsHeld   pgtype.Numeric
	FirstSignal       pgtype.Timestamptz
	LastSignal        pgtype.Timestamptz
}

// The live side of the comparison, grouped so only like is compared with like.
//
// # Why the parameter set is part of the grouping key
//
// A parameter change between two signals leaves two incomparable groups in
// one table looking alike. Averaging across it produces a number describing
// nothing — and it would look exactly like a number describing something.
// The resolved set is recorded on every signal for this reason, and it is
// grouped on here rather than assumed constant.
//
// # What counts
//
// Invalidated outcomes are counted and then excluded from every statistic.
// Their window has missing data, so whether they would have won is not
// knowable; a win rate that quietly counted guesses would be worse than one
// with a smaller sample. They are still reported, because a period where many
// signals were invalidated is itself a finding.
//
// A win is a positive return after modelled cost, which is the same
// definition the backtest's win rate uses. Scalping at these timeframes is
// dominated by cost, so a gross figure would flatter every strategy equally.
func (q *Queries) ReconcileLiveGroups(ctx context.Context, arg ReconcileLiveGroupsParams) ([]ReconcileLiveGroupsRow, error) {
	rows, err := q.db.Query(ctx, reconcileLiveGroups,
		arg.Symbol,
		arg.MarketType,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileLiveGroupsRow{}
	for rows.Next() {
		var i ReconcileLiveGroupsRow
		if err := rows.Scan(
			&i.StrategyName,
			&i.StrategyVersion,
			&i.Params,
			&i.Signals,
			&i.StillOpen,
			&i.Invalidated,
			&i.Resolved,
			&i.Targets,
			&i.Stops,
			&i.Expired,
			&i.Noted,
			&i.Wins,
			&i.Losses,
			&i.AverageWinPct,
			&i.AverageLossPct,
			&i.AverageCostPct,
			&i.AverageEntryPrice,
			&i.AverageBarsHeld,
			&i.FirstSignal,
			&i.LastSignal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
