// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: signals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSignals = `-- name: CountSignals :one
SELECT count(*)::bigint FROM signals
WHERE symbol = $1
  AND market_type = $2
  AND ($3::text IS NULL OR direction = $3::text)
`

type CountSignalsParams struct {
	Symbol     string
	MarketType string
	Direction  pgtype.Text
}

// The size of the collection the page came from, so a client can tell a
// short page from the last page.
func (q *Queries) CountSignals(ctx context.Context, arg CountSignalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSignals, arg.Symbol, arg.MarketType, arg.Direction)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const fetchSignalById = `-- name: FetchSignalById :one
SELECT id, symbol, market_type, timeframe, signal_time, direction, strength, entry_price, stop_loss, take_profit, strategy_name, strategy_version, reason, created_at, signal_price FROM signals WHERE id = $1
`

// One signal, for a delivery worker holding a queue row that points at it.
func (q *Queries) FetchSignalById(ctx context.Context, id pgtype.UUID) (Signal, error) {
	row := q.db.QueryRow(ctx, fetchSignalById, id)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.MarketType,
		&i.Timeframe,
		&i.SignalTime,
		&i.Direction,
		&i.Strength,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.StrategyName,
		&i.StrategyVersion,
		&i.Reason,
		&i.CreatedAt,
		&i.SignalPrice,
	)
	return i, err
}

const insertSignal = `-- name: InsertSignal :one
INSERT INTO signals (
    symbol, market_type, timeframe, signal_time, direction, strength,
    signal_price, entry_price, stop_loss, take_profit,
    strategy_name, strategy_version, reason
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10,
    $11, $12, $13
)
RETURNING id, symbol, market_type, timeframe, signal_time, direction, strength, entry_price, stop_loss, take_profit, strategy_name, strategy_version, reason, created_at, signal_price
`

type InsertSignalParams struct {
	Symbol          string
	MarketType      string
	Timeframe       string
	SignalTime      pgtype.Timestamptz
	Direction       string
	Strength        pgtype.Numeric
	SignalPrice     pgtype.Numeric
	EntryPrice      pgtype.Numeric
	StopLoss        pgtype.Numeric
	TakeProfit      pgtype.Numeric
	StrategyName    string
	StrategyVersion string
	Reason          []byte
}

// Records one strategy decision. The unique constraint on
// (strategy_name, strategy_version, symbol, timeframe, signal_time) makes a
// duplicate insert fail loudly rather than notify the owner twice.
func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, insertSignal,
		arg.Symbol,
		arg.MarketType,
		arg.Timeframe,
		arg.SignalTime,
		arg.Direction,
		arg.Strength,
		arg.SignalPrice,
		arg.EntryPrice,
		arg.StopLoss,
		arg.TakeProfit,
		arg.StrategyName,
		arg.StrategyVersion,
		arg.Reason,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.MarketType,
		&i.Timeframe,
		&i.SignalTime,
		&i.Direction,
		&i.Strength,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.StrategyName,
		&i.StrategyVersion,
		&i.Reason,
		&i.CreatedAt,
		&i.SignalPrice,
	)
	return i, err
}

const listSignals = `-- name: ListSignals :many
SELECT id, symbol, market_type, timeframe, signal_time, direction, strength, entry_price, stop_loss, take_profit, strategy_name, strategy_version, reason, created_at, signal_price FROM signals
WHERE symbol = $1
  AND market_type = $2
  AND ($3::text IS NULL OR direction = $3::text)
ORDER BY signal_time DESC, id
LIMIT $5 OFFSET $4
`

type ListSignalsParams struct {
	Symbol     string
	MarketType string
	Direction  pgtype.Text
	RowOffset  int32
	RowLimit   int32
}

// The signal history, newest first, for a page of the app.
//
// Newest first because that is what a person opening the app wants; the
// offset is what makes older pages reachable without re-reading the newest.
func (q *Queries) ListSignals(ctx context.Context, arg ListSignalsParams) ([]Signal, error) {
	rows, err := q.db.Query(ctx, listSignals,
		arg.Symbol,
		arg.MarketType,
		arg.Direction,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.MarketType,
			&i.Timeframe,
			&i.SignalTime,
			&i.Direction,
			&i.Strength,
			&i.EntryPrice,
			&i.StopLoss,
			&i.TakeProfit,
			&i.StrategyName,
			&i.StrategyVersion,
			&i.Reason,
			&i.CreatedAt,
			&i.SignalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSignalEntryPrice = `-- name: SetSignalEntryPrice :one
UPDATE signals
SET entry_price = $1
WHERE id = $2 AND entry_price IS NULL
RETURNING id, symbol, market_type, timeframe, signal_time, direction, strength, entry_price, stop_loss, take_profit, strategy_name, strategy_version, reason, created_at, signal_price
`

type SetSignalEntryPriceParams struct {
	EntryPrice pgtype.Numeric
	ID         pgtype.UUID
}

// Fill in what a position would have opened at.
//
// It is not knowable when the signal is recorded: the decision is taken on a
// bar's close and the fill is the next bar's open plus slippage, so this is
// written one bar later. Only ever from null, because a second write would
// mean two different answers to a question with one.
func (q *Queries) SetSignalEntryPrice(ctx context.Context, arg SetSignalEntryPriceParams) (Signal, error) {
	row := q.db.QueryRow(ctx, setSignalEntryPrice, arg.EntryPrice, arg.ID)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.MarketType,
		&i.Timeframe,
		&i.SignalTime,
		&i.Direction,
		&i.Strength,
		&i.EntryPrice,
		&i.StopLoss,
		&i.TakeProfit,
		&i.StrategyName,
		&i.StrategyVersion,
		&i.Reason,
		&i.CreatedAt,
		&i.SignalPrice,
	)
	return i, err
}
