// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: signal_outcomes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSignalOutcomes = `-- name: CountSignalOutcomes :one
SELECT count(*)::bigint
FROM signal_outcomes o
JOIN signals s ON s.id = o.signal_id
WHERE s.symbol = $1
  AND s.market_type = $2
  AND ($3::text IS NULL OR o.status = $3::text)
  AND s.signal_time >= $4
  AND s.signal_time <= $5
`

type CountSignalOutcomesParams struct {
	Symbol     string
	MarketType string
	Status     pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
}

func (q *Queries) CountSignalOutcomes(ctx context.Context, arg CountSignalOutcomesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSignalOutcomes,
		arg.Symbol,
		arg.MarketType,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureSignalOutcomes = `-- name: EnsureSignalOutcomes :many
INSERT INTO signal_outcomes (signal_id)
SELECT s.id
FROM signals s
LEFT JOIN signal_outcomes o ON o.signal_id = s.id
WHERE o.signal_id IS NULL
  AND s.symbol = $1
  AND s.market_type = $2
ORDER BY s.signal_time
LIMIT $3
ON CONFLICT (signal_id) DO NOTHING
RETURNING signal_id, status, resolved_at, resolved_price, mae, mfe, bars_held, backtest_would_have, divergence_note, created_at, updated_at
`

type EnsureSignalOutcomesParams struct {
	Symbol     string
	MarketType string
	RowLimit   int32
}

// Open an outcome row for every signal that has none yet.
//
// Done as a set rather than one at a time so a follower starting against a
// table of existing signals — a first deploy, or a restart after an outage —
// picks them up without one round trip each.
//
// The two halves do different jobs and both are needed. The LEFT JOIN filter
// is what makes the batch find signals that still need a row: without it the
// LIMIT would return the oldest signals, which are the ones already followed,
// and a new signal would never be picked up once the backlog exceeded the
// batch size — silently, because every pass would still look like it worked.
// ON CONFLICT DO NOTHING is what makes it safe to run twice: a signal already
// being followed is left exactly as it is, progress included.
func (q *Queries) EnsureSignalOutcomes(ctx context.Context, arg EnsureSignalOutcomesParams) ([]SignalOutcome, error) {
	rows, err := q.db.Query(ctx, ensureSignalOutcomes, arg.Symbol, arg.MarketType, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignalOutcome{}
	for rows.Next() {
		var i SignalOutcome
		if err := rows.Scan(
			&i.SignalID,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedPrice,
			&i.Mae,
			&i.Mfe,
			&i.BarsHeld,
			&i.BacktestWouldHave,
			&i.DivergenceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchOpenSignalOutcomes = `-- name: FetchOpenSignalOutcomes :many
SELECT o.signal_id, o.status, o.resolved_at, o.resolved_price, o.mae, o.mfe, o.bars_held, o.backtest_would_have, o.divergence_note, o.created_at, o.updated_at
FROM signal_outcomes o
JOIN signals s ON s.id = o.signal_id
WHERE o.status = 'open'
  AND s.symbol = $1
  AND s.market_type = $2
ORDER BY s.signal_time, o.signal_id
LIMIT $3
`

type FetchOpenSignalOutcomesParams struct {
	Symbol     string
	MarketType string
	RowLimit   int32
}

// Signals still being followed, oldest first, so a backlog is worked through
// in the order the signals happened.
//
// The signals table is joined to order and filter, and nothing is selected
// from it: the outcome service reads a signal through the signal service's
// usecase, not by reaching into its rows. That costs one point lookup per
// open signal per pass, against a batch of fifty once a minute.
func (q *Queries) FetchOpenSignalOutcomes(ctx context.Context, arg FetchOpenSignalOutcomesParams) ([]SignalOutcome, error) {
	rows, err := q.db.Query(ctx, fetchOpenSignalOutcomes, arg.Symbol, arg.MarketType, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignalOutcome{}
	for rows.Next() {
		var i SignalOutcome
		if err := rows.Scan(
			&i.SignalID,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedPrice,
			&i.Mae,
			&i.Mfe,
			&i.BarsHeld,
			&i.BacktestWouldHave,
			&i.DivergenceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchSignalOutcome = `-- name: FetchSignalOutcome :one
SELECT signal_id, status, resolved_at, resolved_price, mae, mfe, bars_held, backtest_would_have, divergence_note, created_at, updated_at FROM signal_outcomes WHERE signal_id = $1
`

func (q *Queries) FetchSignalOutcome(ctx context.Context, signalID pgtype.UUID) (SignalOutcome, error) {
	row := q.db.QueryRow(ctx, fetchSignalOutcome, signalID)
	var i SignalOutcome
	err := row.Scan(
		&i.SignalID,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedPrice,
		&i.Mae,
		&i.Mfe,
		&i.BarsHeld,
		&i.BacktestWouldHave,
		&i.DivergenceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSignalOutcomes = `-- name: ListSignalOutcomes :many
SELECT o.signal_id, o.status, o.resolved_at, o.resolved_price, o.mae, o.mfe, o.bars_held, o.backtest_would_have, o.divergence_note, o.created_at, o.updated_at
FROM signal_outcomes o
JOIN signals s ON s.id = o.signal_id
WHERE s.symbol = $1
  AND s.market_type = $2
  AND ($3::text IS NULL OR o.status = $3::text)
  AND s.signal_time >= $4
  AND s.signal_time <= $5
ORDER BY s.signal_time DESC, o.signal_id
LIMIT $7 OFFSET $6
`

type ListSignalOutcomesParams struct {
	Symbol     string
	MarketType string
	Status     pgtype.Text
	FromTime   pgtype.Timestamptz
	ToTime     pgtype.Timestamptz
	RowOffset  int32
	RowLimit   int32
}

// Outcomes with the signal they describe, newest first.
//
// The signals table is joined to filter and order, and nothing is selected
// from it: the outcome service reads a signal through the signal service's
// usecase rather than reaching into its rows. That costs one point lookup per
// row of a page bounded at fifty.
func (q *Queries) ListSignalOutcomes(ctx context.Context, arg ListSignalOutcomesParams) ([]SignalOutcome, error) {
	rows, err := q.db.Query(ctx, listSignalOutcomes,
		arg.Symbol,
		arg.MarketType,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignalOutcome{}
	for rows.Next() {
		var i SignalOutcome
		if err := rows.Scan(
			&i.SignalID,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedPrice,
			&i.Mae,
			&i.Mfe,
			&i.BarsHeld,
			&i.BacktestWouldHave,
			&i.DivergenceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSignalOutcome = `-- name: UpdateSignalOutcome :one
UPDATE signal_outcomes
SET status = $1,
    resolved_at = $2,
    resolved_price = $3,
    mae = $4,
    mfe = $5,
    bars_held = $6,
    backtest_would_have = $7,
    divergence_note = $8,
    updated_at = now()
WHERE signal_id = $9
  AND status = 'open'
RETURNING signal_id, status, resolved_at, resolved_price, mae, mfe, bars_held, backtest_would_have, divergence_note, created_at, updated_at
`

type UpdateSignalOutcomeParams struct {
	Status            string
	ResolvedAt        pgtype.Timestamptz
	ResolvedPrice     pgtype.Numeric
	Mae               pgtype.Numeric
	Mfe               pgtype.Numeric
	BarsHeld          int32
	BacktestWouldHave []byte
	DivergenceNote    string
	SignalID          pgtype.UUID
}

// Record progress or a resolution. The same statement serves both: an
// outcome still open carries its running excursions and bar count, and a
// resolved one adds when and where it ended.
//
// The status guard makes resolution one-way at the database rather than by
// convention. Every caller reaches this through FetchOpen, which already
// filters to open rows, so a single collector cannot tell the difference —
// but two collectors will run at once eventually, by accident, during a
// deploy. Without the guard the second one overwrites the first one's
// resolution using a row it read before that resolution existed, and the
// worst case is overwriting `invalidated` with a computed outcome: a
// measurement derived from data known to be incomplete, sitting in the table
// looking exactly like a sound one, with nothing in the row to say otherwise.
//
// Nothing anywhere writes to a resolved outcome on purpose. The reconciliation
// reads them; the accounting is written in the same statement that resolves.
func (q *Queries) UpdateSignalOutcome(ctx context.Context, arg UpdateSignalOutcomeParams) (SignalOutcome, error) {
	row := q.db.QueryRow(ctx, updateSignalOutcome,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedPrice,
		arg.Mae,
		arg.Mfe,
		arg.BarsHeld,
		arg.BacktestWouldHave,
		arg.DivergenceNote,
		arg.SignalID,
	)
	var i SignalOutcome
	err := row.Scan(
		&i.SignalID,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedPrice,
		&i.Mae,
		&i.Mfe,
		&i.BarsHeld,
		&i.BacktestWouldHave,
		&i.DivergenceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
