// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gaps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertGap = `-- name: InsertGap :one
INSERT INTO data_gaps (
    symbol, market_type, timeframe, gap_start, gap_end, note
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, symbol, market_type, timeframe, gap_start, gap_end, detected_at, filled_at, note
`

type InsertGapParams struct {
	Symbol     string
	MarketType string
	Timeframe  string
	GapStart   pgtype.Timestamptz
	GapEnd     pgtype.Timestamptz
	Note       string
}

// Records a detected hole in the candle series so backfill can chase it and
// so a backtest can refuse to trust the period.
func (q *Queries) InsertGap(ctx context.Context, arg InsertGapParams) (DataGap, error) {
	row := q.db.QueryRow(ctx, insertGap,
		arg.Symbol,
		arg.MarketType,
		arg.Timeframe,
		arg.GapStart,
		arg.GapEnd,
		arg.Note,
	)
	var i DataGap
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.MarketType,
		&i.Timeframe,
		&i.GapStart,
		&i.GapEnd,
		&i.DetectedAt,
		&i.FilledAt,
		&i.Note,
	)
	return i, err
}
