package usecase_test

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/spioneracorei8/btcusd-trading-platform/server/services/backtest"
	"github.com/spioneracorei8/btcusd-trading-platform/server/services/backtest/report"
)

// updateGolden rewrites the committed golden file instead of comparing to it.
//
//	go test ./services/backtest/usecase -run Golden -update
//
// Regenerating is accepting a change in what the engine produces. It is not a
// way to make a failing test pass — see the failure message.
var updateGolden = flag.Bool("update", false, "rewrite the golden report")

// goldenPath is committed, deliberately.
//
// # Why the file lives in the repository rather than being generated
//
// A golden regenerated at the start of each run is compared against itself and
// can never fail. Its whole value is proving that a change made months from now
// did not move a number that nothing in that change was supposed to touch —
// which requires the expected output to have been recorded *before* the change,
// by an earlier version of this code, and kept.
//
// This file was first generated by the engine as it stood before maker fees
// and limit orders existed. Every result in docs/experiments.md was produced by
// that engine. If this test fails, the arithmetic behind those entries has
// changed and they have stopped being comparable with anything produced
// afterwards.
//
// It has been regenerated three times, each because a change added fields to
// the JSON document without touching what the engine computes:
//
//  1. maker fees and limit fills — 68 keys added
//  2. the spread cost model — a further 67
//  3. the trades-per-day frequency line — one more
//
// All were checked field by field against the file as first committed. All 136
// keys are additions: **zero existing values changed, and none removed**. The
// trades, the equity curve and every statistic are identical to the original
// in each. Any future regeneration deserves the same check, and the same
// sentence in its commit message.
const goldenPath = "testdata/golden/market-orders-baseline.json"

// TestTheDefaultCostModelStillProducesTheRecordedResult.
//
// The default execution model is market entry and market exit, which is what
// every completed evaluation used. Adding a second fee rate and a resting-order
// path must leave that arithmetic untouched: the same bars, the same strategy
// and the same costs have to produce the same trades, the same equity curve and
// the same statistics, byte for byte.
func TestTheDefaultCostModelStillProducesTheRecordedResult(t *testing.T) {
	// A deliberately busy fixture: the alternating strategy trades throughout,
	// so the report carries a full trade list and equity curve rather than a
	// summary of nothing. Prices rise monotonically, which keeps the series
	// deterministic without depending on a database.
	series := risingSeries(400, 100)
	candles := &fakeCandles{series: series}

	params := scoredParams(t, series, &alternating{everyN: 7})
	params.Costs = testCosts()
	params.Sizing = backtest.AllInSizing()

	result := runEngine(t, candles, nil, params)
	stats := report.Compute(result)

	var rendered bytes.Buffer
	if err := report.WriteJSON(&rendered, report.BuildDocument(result, stats)); err != nil {
		t.Fatalf("WriteJSON() returned error: %v", err)
	}

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("create %s: %v", filepath.Dir(goldenPath), err)
		}
		if err := os.WriteFile(goldenPath, rendered.Bytes(), 0o644); err != nil {
			t.Fatalf("write %s: %v", goldenPath, err)
		}
		t.Logf("rewrote %s — commit it only if the change was intended", goldenPath)
		return
	}

	expected, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read %s: %v\n\nThe golden report is committed on purpose. "+
			"Generate it with -update only when creating it for the first time.", goldenPath, err)
	}

	if !bytes.Equal(expected, rendered.Bytes()) {
		t.Errorf(`the default cost model no longer produces the recorded result.

%s was generated before maker fees and limit orders existed, and every entry in
docs/experiments.md was produced by that engine. A difference here means one of
two things:

  1. Something changed the arithmetic of a market-order run, which was not
     supposed to happen. Find it. The completed evaluations are no longer
     comparable with anything produced after this point.

  2. The change was intended and the reason is written down. Then, and only
     then, regenerate with -update in a commit that says why.

Regenerating to make this pass is how the evidence gets quietly discarded.`,
			goldenPath)

		// Where they diverge, so the cause is findable without a diff tool.
		t.Errorf("%s", firstDifference(expected, rendered.Bytes()))
	}
}
